In [2]:
import duckdb as ddb
import pandas as pd

con = ddb.connect(database=":memory:")

con.sql("""
CREATE TABLE program_beslut AS
    FROM 'data/resultat-ansokningsomgang-2020-2024-beslut.csv';
CREATE TABLE program_kommun AS
    FROM 'data/resultat-ansokningsomgang-2020-2024-diarie_kommun.csv';

CREATE TABLE kurser_beslut AS
    FROM 'data/resultat-for-kurser-inom-yh-2024-beslut.csv';
CREATE TABLE kurser_kommun AS
    FROM 'data/resultat-for-kurser-inom-yh-2024-diarie_kommun.csv';

CREATE TABLE kommun_lan AS
    FROM 'data/kommunlankod-2025.csv';       
""")

In [3]:
con.sql("""select * from kurser_beslut""").describe()
# con.sql("""select * from kurser_beslut""").columns

┌─────────┬───────────────┬──────────────────┬─────────┬─────────────────────────────────┬─────────────────────────────────────────────────┬───────────────────┬───────────────────┬────────────────────┬──────────────────────────┬────────────────────┬──────────────┬───────────┬────────────────────┬────────────────┐
│  aggr   │ Diarienummer  │ Ansökningsomgång │ Beslut  │      Utbildningsanordnare       │                 Utbildningsnamn                 │ Utbildningsområde │     YH-poäng      │ Beviljade platser  │ Beviljade platser totalt │       Start        │     Län      │  Kommun   │   Antal kommuner   │ Flera kommuner │
│ varchar │    varchar    │      double      │ varchar │             varchar             │                     varchar                     │      varchar      │      double       │       double       │          double          │       double       │   varchar    │  varchar  │       double       │    varchar     │
├─────────┼───────────────┼──────────────────┼─────────┼─────────────────────────────────┼─────────────────────────────────────────────────┼───────────────────┼───────────────────┼────────────────────┼──────────────────────────┼────────────────────┼──────────────┼───────────┼────────────────────┼────────────────┤
│ count   │ 1090          │           1090.0 │ 1090    │ 1090                            │ 1090                                            │ 1090              │            1090.0 │             1090.0 │                   1090.0 │             1090.0 │ 901          │ 901       │             1090.0 │ 1090           │
│ mean    │ NULL          │           2024.0 │ NULL    │ NULL                            │ NULL                                            │ NULL              │ 41.47798165137615 │ 21.980733944954128 │        36.19266055045872 │ 2024.2018348623853 │ NULL         │ NULL      │ 1.3412844036697247 │ NULL           │
│ stddev  │ NULL          │              0.0 │ NULL    │ NULL                            │ NULL                                            │ NULL              │ 18.64776619782181 │ 20.461493666408217 │        36.62709536730105 │ 0.4015538349292432 │ NULL         │ NULL      │ 0.8682979994370141 │ NULL           │
│ min     │ MYH 2024/1000 │           2024.0 │ false   │ ABF Göteborg Vuxenutbildning AB │ 3D Clo Fördjupning Modedesigner                 │ Data/IT           │              10.0 │                0.0 │                      0.0 │             2024.0 │ Blekinge     │ Angered   │                1.0 │ false          │
│ max     │ MYH 2024/999  │           2024.0 │ true    │ Östsvenska Yrkeshögskolan AB    │ Återbruk och cirkularitet inom bygg & fastighet │ Transporttjänster │              99.0 │              100.0 │                    160.0 │             2025.0 │ Östergötland │ Östersund │                5.0 │ true           │
│ median  │ NULL          │           2024.0 │ NULL    │ NULL                            │ NULL                                            │ NULL              │              40.0 │               25.0 │                     30.0 │             2024.0 │ NULL         │ NULL      │                1.0 │ NULL           │
└─────────┴───────────────┴──────────────────┴─────────┴─────────────────────────────────┴─────────────────────────────────────────────────┴───────────────────┴───────────────────┴────────────────────┴──────────────────────────┴────────────────────┴──────────────┴───────────┴────────────────────┴────────────────┘

In [4]:
def get_utbildningsanordnare(con):
    rel = con.sql("""
    select distinct Utbildningsanordnare
    from kurser_beslut
    order by Utbildningsanordnare
    """)
    return [i[0] for i in rel.fetchall()]


get_utbildningsanordnare(con)

['ABF Göteborg Vuxenutbildning AB',
 'AGSTU AB',
 'ALEA Kompetenshöjning AB',
 'AVT AB',
 'Ai Högskolan Sverige AB',
 'Almost There AB',
 'Amsac AB',
 'Angered folkhögskola',
 'Arboga kommun, Vuxenutbildningen',
 'Arvika Kommun',
 'Bergsskolan Kompetensutveckling AB',
 'Blue Peak AB',
 'Borås Stad - Yrkeshögskolan i Borås',
 'Båstads kommun Akademi Båstad',
 'Cady training utbildningar AB',
 'Campus Ljungby AB',
 'Campus Nyköping',
 'Campus Nynäshamn',
 'Campus Varberg/Varbergs kommun',
 'Changemaker Educations AB',
 'Chas Academy AB',
 'Dans i Göteborg AB',
 'Digitala lyftet i Sverige AB',
 'Dille Gård AB',
 'EBT Academy AB',
 'EC Utbildning AB Göteborg',
 'EC Utbildning AB Malmö',
 'EC Utbildning AB Stockholm',
 'EC Utbildning AB Örebro',
 'East Sweden Business School AB',
 'EdUP Group AB',
 'Edugrade AB',
 'Elevera Education Group',
 'Enköpings kommun, Yrkeshögskolan i Enköping',
 'Equine Academy Sweden AB',
 'Eriksmåla Ridklubb',
 'Falkenbergs kommun',
 'Fastighetsakademin Sverige AB',
 'Finska folkhögskolans stiftelse',
 'Folktandvården Västra Götalandsregionen, Tandsköterskeutbildningen',
 'Folkuniversitetet - Kursverksamheten vid Lunds Universitet',
 'Folkuniversitetet - Kursverksamheten vid Stockholms universitet',
 'Folkuniversitetet - Stiftelsen Kursverksamheten vid Uppsala universitetet',
 'Folkuniversitetet Kursverksamheten vid Göteborgs universitet',
 'Folkuniversitetet – Kursverksamheten vid Umeå Universitet',
 'Fordonsakademin Sverige AB',
 'Funka Academy AB',
 'Företagsekonomiska Institutet 1888 AB',
 'Företagsuniversitetet AB',
 'Gislaveds Kommun Vuxenutbildningen /Hph',
 'Grit Academy',
 'Gunnebo Slott och Trädgårdar AB',
 'Göteborgs Stad, Yrgo',
 'Göteborgs Tekniska College AB',
 'Handelsakademin i Göteborg AB',
 'Hermods AB Göteborg',
 'Hermods AB Helsingborg',
 'Hermods AB Karlskrona',
 'Hermods AB Lund',
 'Hermods AB Malmö',
 'Hermods AB Stockholm',
 'Hermods AB Umeå',
 'Hermods AB Örebro',
 'Hermods AB Östersund',
 'Hyper Island Program AB - Karlskrona',
 'Hyper Island Program AB - Stockholm',
 'Härnösands kommun, Yrkeshögskolan',
 'Härryda kommun, Yrkeshögskolan i Mölnlycke',
 'Högskolan Kristianstad Uppdrag AB',
 'IHM Business School AB Göteborg',
 'INSU AB',
 'IT-Högskolan Stockholm AB',
 'IT-Högskolan Sverige AB',
 'ITH, Institutet För Tillämpad Hydraulik',
 'Idéutvecklarna AB',
 'Information & kompetensförsörjning i Sverige Aktiebolag',
 'Iris Hadar AB',
 'Iterum Education AB',
 'JAG Utbildning AB',
 'JENSEN Education School AB',
 'Ja&Ja AB',
 'John Ericsson Institutet',
 'KYH AB',
 'Karlskoga kommun',
 'Karlsson Climate AB',
 'Klippans kommun, Flygteknikcenter',
 'KompetensUtvecklingsInstitutet Sverige AB',
 'Kulturama',
 'Kunskapsförbundet Väst, Vuxenutbildningen',
 'Kunskapsgruppen Yrkeshögskola Sverige AB',
 'Köpings kommun',
 'LAVI gruppen AB',
 'Landskrona Stad, Yrkeshögskolan Landskrona',
 'Lernia Utbildning AB',
 'Lexicon Yrkeshögskola AB',
 'Lidköpings kommun Campus Lidköping',
 'Malmö Tillskärarakademi AB',
 'Mariestads kommun, Dacapo Mariestad',
 'MedLearn AB',
 'Medborgarskolan i Stockholm - Påhlmans Handelsinstitut ',
 'Medieinstitutet i Sverige AB',
 'Montico Kompetensutveckling AB',
 'Movant AB',
 'Mölk Utbildning AB',
 'NBI i Sverige AB ',
 'Nackademin AB',
 'Nava Group AB',
 'Nercia Utbildning',
 'Newton Kompetensutveckling AB',
 'Nässjö kommun, Nässjöakademin',
 'Nätverkstan Kultur AB',
 'Omsorgsförlaget',
 'One Academy AB',
 'Oskarshamns kommun, Nova Utbildning, FoU & Affärsutveckling',
 'Plushögskolan AB - Affärshögskolan',
 'Plushögskolan AB - Teknikhögskolan',
 'Plushögskolan AB - Vårdyrkeshögskolan',
 'Region Kronoberg, YH Region Kronoberg',
 'Rädda Barnen Välfärd',
 'Skövde kommun, Skövde Yrkeshögskola',
 'Sociala Tjänstehundar i Sverige AB/Svenska Terapihundskolan',
 'Solarspect Sverige ab',
 'Sollefteå kommun - Reveljen',
 'Step by Step Competence AB',
 'Stiftelsen Capellagården',
 'Stiftelsen PROTEKO - Nordiska Textilakademin',
 'Stiftelsen Stockholms Tekniska Institut',
 'Stockholm School of Business',
 'Stockholms Internationella Handelsskola AB',
 'Stockholms Stadsmission',
 'Stockholms Tillskärarakademi ',
 'Stockholms Trafiklärarutbildning',
 'Stockholms stad, Frans Schartaus Handelsinstitut',
 'Sundsgårdens folkhögskola',
 'Sunne kommun/Brobygrafiska',
 'Svenska Ledargruppen AB',
 'Svenska Trädmästarna AB',
 'Sverigehälsan AB',
 'Sveriges Yrkeshögskola AB - Göteborg Yrkeshögskola',
 'Sveriges Yrkeshögskola AB - Malmö Yrkeshögskola',
 'Sveriges Yrkeshögskola AB - Stockholm Yrkeshögskola',
 'Sälj & Marknadshögskolan i Sverige AB',
 'TCC Sverige AB',
 'TEC Travel Education Centre AB',
 'TUC Sweden AB - Yrkeshögskola',
 'Technigo AB',
 'Tekniska Högskolan i Jönköping AB',
 'Tension Education AB',
 'Torsta AB',
 'Trelleborgs kommun',
 'Uddevalla kommun, Uddevalla Yrkeshögskola',
 'Unestål Education',
 'Vilhelmina kommun, Vilhelmina Lärcentrum',
 'Värna',
 'Västerås Stad/Barn- och Utbildningsförvaltningen/Västerås Yrkeshögskola',
 'Västra Götalands läns landsting, Biologiska Yrkeshögskolan i Skara - BYS',
 'WeWon Media Group AB',
 'XeDrix AB',
 'Xenter Yrkeshögskola ',
 'YH Akademin AB',
 'YH Akademin(Marknad)',
 'Yrkeshögskola Campus Mölndal',
 'Yrkesutbildaren Habo AB                     ',
 'Älmhults kommun, Haganässkolan',
 'Åsbro Kursgård AB',
 'Östsvenska Yrkeshögskolan AB']

In [5]:
def create_df_utbildningsomrade_beviljade(con, utbildningsanordnare: list[str] | None = None, year=2024):
    rel = con.sql(
        """
    select
        Utbildningsområde,
        count(*) as Beviljade
    from kurser_beslut
    where
        ( $utb IS NULL OR Utbildningsanordnare = ANY($utb) )
        and Ansökningsomgång = $year
        and Beslut = true
    group by Utbildningsområde
    order by Beviljade desc, Utbildningsområde
    ;""",
        params={"year": year, "utb": utbildningsanordnare},
    )
    return rel.df().set_index(["Utbildningsområde"])


create_df_utbildningsomrade_beviljade(con)

                                              Beviljade
Utbildningsområde
Ekonomi, administration och försäljning             171
Data/IT                                             111
Teknik och tillverkning                             106
Samhällsbyggnad och byggteknik                       93
Hälso- och sjukvård samt socialt arbete              81
Hotell, restaurang och turism                        19
Lantbruk, djurvård, trädgård, skog och fiske         18
Pedagogik och undervisning                           15
Journalistik och information                         11
Juridik                                              11
Säkerhetstjänster                                    11
Kultur, media och design                             10
Transporttjänster                                     4

In [6]:
create_df_utbildningsomrade_beviljade(con, ["Stiftelsen Stockholms Tekniska Institut"])

                                Beviljade
Utbildningsområde
Data/IT                                 7
Samhällsbyggnad och byggteknik          6

In [7]:
def create_df_utbildningsomrade_avslag(con, utbildningsanordnare: list[str] | None = None, year=2024):
    rel = con.sql(
        """
    select
        Utbildningsområde,
        count(*) as Avslag
    from kurser_beslut
    where
        ( $utb IS NULL OR Utbildningsanordnare = ANY($utb) )
        and Ansökningsomgång = $year
        and Beslut = false
    group by Utbildningsområde
    order by Avslag desc, Utbildningsområde
    ;""",
        params={"year": year, "utb": utbildningsanordnare},
    )
    return rel.df().set_index("Utbildningsområde")


create_df_utbildningsomrade_avslag(con)

                                              Avslag
Utbildningsområde
Ekonomi, administration och försäljning          112
Data/IT                                           84
Hälso- och sjukvård samt socialt arbete           53
Teknik och tillverkning                           51
Samhällsbyggnad och byggteknik                    41
Lantbruk, djurvård, trädgård, skog och fiske      24
Pedagogik och undervisning                        18
Säkerhetstjänster                                 11
Hotell, restaurang och turism                      9
Juridik                                            9
Kultur, media och design                           9
Journalistik och information                       5
Friskvård och kroppsvård                           2
Transporttjänster                                  1

In [8]:
create_df_utbildningsomrade_avslag(con, ["Stiftelsen Stockholms Tekniska Institut"])

                                Avslag
Utbildningsområde
Data/IT                              1
Samhällsbyggnad och byggteknik       1

In [9]:
def create_df_utbildningsomrade_beslut(con, beslut=True, utbildningsanordnare: list[str] | None = None, year=2024):
    rel = con.sql(
        """
    select
        Utbildningsområde,
        count(*) as Beslut
    from kurser_beslut
    where
        ( $utb IS NULL OR Utbildningsanordnare = ANY($utb) )
        and Ansökningsomgång = $year
        and Beslut = $beslut
    group by Utbildningsområde
    order by Beslut desc, Utbildningsområde
    ;""",
        params={"beslut": beslut, "year": year, "utb": utbildningsanordnare},
    )

    df_rel: pd.Dataframe = rel.df().set_index("Utbildningsområde")
    return df_rel.rename(columns={"Beslut": "Beviljade" if beslut else "Avslag"})


create_df_utbildningsomrade_beslut(con, beslut=False)

                                              Avslag
Utbildningsområde
Ekonomi, administration och försäljning          112
Data/IT                                           84
Hälso- och sjukvård samt socialt arbete           53
Teknik och tillverkning                           51
Samhällsbyggnad och byggteknik                    41
Lantbruk, djurvård, trädgård, skog och fiske      24
Pedagogik och undervisning                        18
Säkerhetstjänster                                 11
Hotell, restaurang och turism                      9
Juridik                                            9
Kultur, media och design                           9
Journalistik och information                       5
Friskvård och kroppsvård                           2
Transporttjänster                                  1

In [10]:
def get_kurser_antal(con):
    rel = con.sql("""
    select
        (select count(*) from kurser_beslut) as "Kurs-ansökningar",
        (select count(*) from kurser_kommun) as "Kurs-ansökningar, alla kommuner"
    """)
    return rel.fetchone()


get_kurser_antal(con)

(1090, 1202)

In [11]:
def get_utbildningsomraden(con):
    rel = con.sql("""
    select distinct Utbildningsområde
    from kurser_beslut
    order by Utbildningsområde
    """)
    return [i[0] for i in rel.fetchall()]


get_utbildningsomraden(con)

['Data/IT',
 'Ekonomi, administration och försäljning',
 'Friskvård och kroppsvård',
 'Hotell, restaurang och turism',
 'Hälso- och sjukvård samt socialt arbete',
 'Journalistik och information',
 'Juridik',
 'Kultur, media och design',
 'Lantbruk, djurvård, trädgård, skog och fiske',
 'Pedagogik och undervisning',
 'Samhällsbyggnad och byggteknik',
 'Säkerhetstjänster',
 'Teknik och tillverkning',
 'Transporttjänster']

In [12]:
def create_df_kurser_beviljade(con, utbildningsomrade: list[str] | None = None):
    rel = con.sql(
        """
    select
        Utbildningsanordnare,
        -- Utbildningsområde,
        count(*) as Ansökningar,
        sum(case when Beslut = true then 1 else 0 end)::integer as Beviljade,
        round(100.00 * sum(case when Beslut = true then 1 else 0 end) / count(*),1) as "Beviljade %",
    from kurser_beslut
    where ( $areas IS NULL OR Utbildningsområde = ANY($areas) )
    group by Utbildningsanordnare, Utbildningsområde
    order by "Beviljade %" desc, Ansökningar desc, Utbildningsanordnare
    """,
        params={"areas": utbildningsomrade},
    )
    return rel.df().set_index("Utbildningsanordnare")


create_df_kurser_beviljade(con, ["Data/IT"]).head(20)

,Ansökningar,Beviljade,Beviljade %
Utbildningsanordnare,,,
IT-Högskolan Sverige AB,11,11,100.0
Nackademin AB,9,9,100.0
YH Akademin AB,8,8,100.0
Handelsakademin i Göteborg AB,6,6,100.0
EC Utbildning AB Göteborg,4,4,100.0
AGSTU AB,2,2,100.0
Folkuniversitetet - Stiftelsen Kursverksamheten vid Uppsala universitetet,2,2,100.0
Hermods AB Örebro,2,2,100.0
Hyper Island Program AB - Karlskrona,2,2,100.0
IHM Business School AB Göteborg,2,2,100.0
"Stockholms stad, Frans Schartaus Handelsinstitut",2,2,100.0
Stockholm School of Business,1,1,100.0
Stockholms Internationella Handelsskola AB,1,1,100.0
Sveriges Yrkeshögskola AB - Göteborg Yrkeshögskola,1,1,100.0
Stiftelsen Stockholms Tekniska Institut,8,7,87.5
Medieinstitutet i Sverige AB,14,12,85.7
Sveriges Yrkeshögskola AB - Malmö Yrkeshögskola,6,4,66.7
EC Utbildning AB Stockholm,3,2,66.7
Företagsekonomiska Institutet 1888 AB,3,2,66.7
Företagsuniversitetet AB,3,2,66.7

In [13]:
create_df_kurser_beviljade(con, None).head(20)

                                           Ansökningar  Beviljade  Beviljade %
Utbildningsanordnare
KompetensUtvecklingsInstitutet Sverige AB           15         15        100.0
Nackademin AB                                       13         13        100.0
IT-Högskolan Sverige AB                             11         11        100.0
Nackademin AB                                        9          9        100.0
Sverigehälsan AB                                     9          9        100.0
Lexicon Yrkeshögskola AB                             8          8        100.0
Medieinstitutet i Sverige AB                         8          8        100.0
YH Akademin AB                                       8          8        100.0
One Academy AB                                       7          7        100.0
ALEA Kompetenshöjning AB                             6          6        100.0
Amsac AB                                             6          6        100.0
Handelsakademin i Göteborg AB                        6          6        100.0
Malmö Tillskärarakademi AB                           6          6        100.0
Mariestads kommun, Dacapo Mariestad                  6          6        100.0
MedLearn AB                                          6          6        100.0
Montico Kompetensutveckling AB                       5          5        100.0
ALEA Kompetenshöjning AB                             4          4        100.0
Campus Nyköping                                      4          4        100.0
EC Utbildning AB Göteborg                            4          4        100.0
Fastighetsakademin Sverige AB                        4          4        100.0

In [14]:
con.sql("""select * from program_beslut""").describe()

┌─────────┬───────────────────┬────────────────────────────────────────────────────────────────────┬──────────────┬──────────────┬────────────────────┬────────────────┬───────────────────┬────────────┬────────────────────┬─────────────────────────────────┬───────────────┬───────────────────────────┬───────────────────────────────┬──────────────────────┬──────────────────────────┬─────────────────────────────────────┬────────────────────┬───────────────┬─────────┐
│  aggr   │ Utbildningsområde │                          Utbildningsnamn                           │     Län      │    Kommun    │   Antal kommuner   │ Flera kommuner │     YH-poäng      │ Studieform │    Studietakt %    │      Utbildningsanordnare       │ Huvudmannatyp │ Sökta utbildningsomgångar │ Beviljade utbildningsomgångar │ Sökta platser totalt │ Beviljade platser totalt │ Sökta platser per utbildningsomgång │  Ansökningsomgång  │ Diarienummer  │ Beslut  │
│ varchar │      varchar      │                              varchar                               │   varchar    │   varchar    │       double       │    varchar     │      double       │  varchar   │       double       │             varchar             │    varchar    │          double           │            double             │        double        │          double          │               double                │       double       │    varchar    │ varchar │
├─────────┼───────────────────┼────────────────────────────────────────────────────────────────────┼──────────────┼──────────────┼────────────────────┼────────────────┼───────────────────┼────────────┼────────────────────┼─────────────────────────────────┼───────────────┼───────────────────────────┼───────────────────────────────┼──────────────────────┼──────────────────────────┼─────────────────────────────────────┼────────────────────┼───────────────┼─────────┤
│ count   │ 7640              │ 7640                                                               │ 7640         │ 7640         │             7640.0 │ 7640           │            7640.0 │ 7640       │             7640.0 │ 7640                            │ 7640          │                    7640.0 │                        7640.0 │               7640.0 │                   7640.0 │                              7640.0 │             7640.0 │ 7640          │ 7640    │
│ mean    │ NULL              │ NULL                                                               │ NULL         │ NULL         │ 1.7663612565445026 │ NULL           │ 353.5969895287958 │ NULL       │  95.12434554973822 │ NULL                            │ NULL          │        3.6657068062827225 │            0.9267015706806283 │    92.90353403141361 │       23.564659685863873 │                  25.364005235602093 │  2021.791884816754 │ NULL          │ NULL    │
│ stddev  │ NULL              │ NULL                                                               │ NULL         │ NULL         │ 1.5696907844064738 │ NULL           │ 88.82489833695931 │ NULL       │ 14.425471790646563 │ NULL                            │ NULL          │        0.9533026066420978 │             1.387626622080571 │   45.391217216730816 │       38.489291846850016 │                  10.276047854234903 │ 1.4112064740312367 │ NULL          │ NULL    │
│ min     │ Data/IT           │ \nSpecialistundersköterska med inriktning digital hälsa och teknik │ Blekinge     │ Alingsås     │                1.0 │ false          │             100.0 │ Bunden     │               50.0 │ ABF Göteborg Vuxenutbildning AB │ Kommun        │                       1.0 │                           0.0 │                  5.0 │                      0.0 │                                 2.0 │             2020.0 │ MYH 2020/1698 │ false   │
│ max     │ Övrigt            │ Återbruksstrateg                                                   │ Östergötland │ Östra Göinge │               10.0 │ true           │             999.0 │ Distans    │              100.0 │ Östsvenska Yrkeshögskolan AB    │ Statlig       │                       5.0 │                           5.0 │                175.0 │                    175.0 │                                35.0 │             2024.0 │ MYH 2024/4278 │ true    │
│ median  │ NULL              │ NULL                                                               │ NULL         │ NULL         │                1.0 │ NULL           │             400.0 │ NULL       │              100.0 │ NULL                            │ NULL          │                       3.0 │                           0.0 │                100.0 │                      0.0 │                                30.0 │             2022.0 │ NULL          │ NULL    │
└─────────┴───────────────────┴────────────────────────────────────────────────────────────────────┴──────────────┴──────────────┴────────────────────┴────────────────┴───────────────────┴────────────┴────────────────────┴─────────────────────────────────┴───────────────┴───────────────────────────┴───────────────────────────────┴──────────────────────┴──────────────────────────┴─────────────────────────────────────┴────────────────────┴───────────────┴─────────┘

In [15]:
def create_df_lan_utbildningar(con):
    rel = con.sql("""
    select
        Län,
        count(distinct Diarienummer) as "Antal beviljade utbildningar",
    from program_beslut
    where
        Ansökningsomgång = 2024
        and beslut = true
    group by Län
    order by "Antal beviljade utbildningar" desc
    """)
    return rel.df().set_index("Län")


create_df_lan_utbildningar(con).head(20)

                 Antal beviljade utbildningar
Län
Stockholm                                  82
Flera kommuner                             65
Västra Götaland                            63
Skåne                                      37
Östergötland                               16
Jönköping                                  13
Örebro                                     10
Västernorrland                              6
Kalmar                                      5
Kronoberg                                   5
Västmanland                                 5
Gävleborg                                   5
Västerbotten                                4
Halland                                     4
Dalarna                                     4
Värmland                                    4
Norrbotten                                  4
Uppsala                                     4
Södermanland                                3
Blekinge                                    3

In [16]:
def create_df_lan_utbildningsanordnare(
    con,
    lan: list[str] | None = None,
    beslut: bool | None = None,
    year=2024,
):
    if not lan:
        lan = None
    rel = con.sql(
        """
    select
        Län,
        count(distinct Utbildningsanordnare) as "Antal utbildningsanordnare",
    from program_beslut
    where
        Ansökningsomgång = $year
        and ( $beslut IS NULL OR Beslut = $beslut )
        and ( $lan IS NULL OR Län = ANY($lan) )
    group by Län
    order by "Antal utbildningsanordnare" desc
    """,
        params={"year": year, "lan": lan, "beslut": beslut},
    )
    return rel.df().set_index("Län")


create_df_lan_utbildningsanordnare(con, []).head(20)

                 Antal utbildningsanordnare
Län
Stockholm                                77
Flera kommuner                           75
Västra Götaland                          57
Skåne                                    52
Västerbotten                             17
Östergötland                             15
Västmanland                              13
Örebro                                   12
Västernorrland                           11
Blekinge                                 10
Jönköping                                10
Norrbotten                                9
Dalarna                                   8
Halland                                   8
Kalmar                                    8
Uppsala                                   8
Gävleborg                                 8
Kronoberg                                 8
Värmland                                  8
Södermanland                              6

In [17]:
def create_df_lan_utbildningar(
    con,
    lan: list[str] | None = None,
    beslut: bool | None = None,
    year=2024,
):
    if not lan:
        lan = None

    rel = con.sql(
        """
    select
        Län,
        count(distinct Diarienummer) as "Utbildningar, antal ansökta",
    from program_beslut
    where
        Ansökningsomgång = $year
        and ( $beslut IS NULL OR Beslut = $beslut )
        and "Flera kommuner" = False
        and ( $lan IS NULL OR Län = ANY($lan) )
    group by Län
    order by "Utbildningar, antal ansökta" desc
    """,
        params={"year": year, "lan": lan, "beslut": beslut},
    )

    df_rel: pd.Dataframe = rel.df().set_index("Län")
    if beslut is not None:
        df_rel = df_rel.rename(
            columns={
                "Utbildningar, antal ansökta": "Utbildningar, antal beviljade"
                if beslut
                else "Utbildningar, antal avslag",
            }
        )
    return df_rel


create_df_lan_utbildningar(con, []).head(20)

                 Utbildningar, antal ansökta
Län
Stockholm                                313
Västra Götaland                          212
Skåne                                    137
Östergötland                              41
Jönköping                                 39
Västernorrland                            28
Västerbotten                              26
Västmanland                               25
Örebro                                    24
Värmland                                  17
Halland                                   15
Blekinge                                  15
Norrbotten                                15
Kronoberg                                 13
Södermanland                              12
Gävleborg                                 12
Uppsala                                   11
Kalmar                                    10
Dalarna                                    9
Jämtland                                   6

In [18]:
create_df_lan_utbildningar(con, beslut=False).head(20)

                 Utbildningar, antal avslag
Län
Stockholm                               231
Västra Götaland                         149
Skåne                                   100
Jönköping                                26
Östergötland                             25
Västerbotten                             22
Västernorrland                           22
Västmanland                              20
Örebro                                   14
Värmland                                 13
Blekinge                                 12
Norrbotten                               11
Halland                                  11
Södermanland                              9
Kronoberg                                 8
Gävleborg                                 7
Uppsala                                   7
Kalmar                                    5
Dalarna                                   5
Jämtland                                  4

In [19]:
create_df_lan_utbildningar(con, ["Skåne", "Norrbotten"]).head(20)

            Utbildningar, antal ansökta
Län
Skåne                               137
Norrbotten                           15

In [20]:
con.sql("""select * from program_kommun""").describe()

┌─────────┬───────────────┬──────────────┬──────────────┬─────────┐
│  aggr   │ Diarienummer  │    Kommun    │     Län      │ Beslut  │
│ varchar │    varchar    │   varchar    │   varchar    │ varchar │
├─────────┼───────────────┼──────────────┼──────────────┼─────────┤
│ count   │ 8589          │ 8589         │ 8589         │ 8589    │
│ mean    │ NULL          │ NULL         │ NULL         │ NULL    │
│ stddev  │ NULL          │ NULL         │ NULL         │ NULL    │
│ min     │ MYH 2020/1698 │ Alingsås     │ Blekinge     │ false   │
│ max     │ MYH 2024/4278 │ Östra Göinge │ Östergötland │ true    │
│ median  │ NULL          │ NULL         │ NULL         │ NULL    │
└─────────┴───────────────┴──────────────┴──────────────┴─────────┘

In [21]:
con.sql("""select * from kommun_lan""").describe()

┌─────────┬────────────┬──────────────┬───────────────────┬───────────────────┐
│  aggr   │   Kommun   │     Län      │     Län, namn     │        Kod        │
│ varchar │  varchar   │   varchar    │      varchar      │      double       │
├─────────┼────────────┼──────────────┼───────────────────┼───────────────────┤
│ count   │ 290        │ 311          │ 311               │             311.0 │
│ mean    │ NULL       │ NULL         │ NULL              │ 1289.668810289389 │
│ stddev  │ NULL       │ NULL         │ NULL              │ 771.7981703567322 │
│ min     │ Ale        │ Blekinge     │ Blekinge län      │               1.0 │
│ max     │ Övertorneå │ Östergötland │ Östergötlands län │            2584.0 │
│ median  │ NULL       │ NULL         │ NULL              │            1401.0 │
└─────────┴────────────┴──────────────┴───────────────────┴───────────────────┘

In [22]:
con.sql(
    """
    select p.*, k.Län
    from program_kommun as p
    left join kommun_lan as k
        on p.Kommun = k.Kommun
    where p.Län != k.Län
    ;"""
).df()

Empty DataFrame
Columns: [Diarienummer, Kommun, Län, Beslut, Län_1]
Index: []

In [23]:
con.sql(
    """
    with kurser_alla_kommuner as (

    select
        "Diarienummer",
        "Ansökningsomgång",
        "Beslut",
        "Utbildningsanordnare",
        "Utbildningsnamn",
        "Utbildningsområde",
        "YH-poäng",
        "Beviljade platser",
        "Beviljade platser totalt",
        "Start",
        "Län",
        "Kommun",
        "Antal kommuner",
        "Flera kommuner"
    from kurser_beslut kb
    where
        "Flera kommuner" is not TRUE
    
    union all

    select
        kb."Diarienummer",
        kb."Ansökningsomgång",
        kb."Beslut",
        kb."Utbildningsanordnare",
        kb."Utbildningsnamn",
        kb."Utbildningsområde",
        kb."YH-poäng",
        kb."Beviljade platser",
        kb."Beviljade platser totalt",
        kb."Start",
        kk."Län",                -- kurser_kommun
        kk."Kommun",             -- kurser_kommun
        kb."Antal kommuner",
        kb."Flera kommuner"
    from kurser_beslut kb
    join kurser_kommun kk
        on kk."Diarienummer" = kb."Diarienummer"
     where
        kb."Flera kommuner" is TRUE

    )

    select *
    from kurser_alla_kommuner
    order by "Diarienummer"
    ;"""
).df()

,Diarienummer,Ansökningsomgång,Beslut,Utbildningsanordnare,Utbildningsnamn,Utbildningsområde,YH-poäng,Beviljade platser,Beviljade platser totalt,Start,Län,Kommun,Antal kommuner,Flera kommuner
0,MYH 2024/1000,2024,False,Changemaker Educations AB,Futuregames Accessible Game Production,Juridik,25,0,0,2024,Stockholm,Stockholm,3,True
1,MYH 2024/1000,2024,False,Changemaker Educations AB,Futuregames Accessible Game Production,Juridik,25,0,0,2024,Norrbotten,Boden,3,True
2,MYH 2024/1000,2024,False,Changemaker Educations AB,Futuregames Accessible Game Production,Juridik,25,0,0,2024,Skåne,Malmö,3,True
3,MYH 2024/1001,2024,False,Changemaker Educations AB,Futuregames Inclusive Game Development,"Ekonomi, administration och försäljning",25,0,0,2024,Skåne,Malmö,3,True
4,MYH 2024/1001,2024,False,Changemaker Educations AB,Futuregames Inclusive Game Development,"Ekonomi, administration och försäljning",25,0,0,2024,Norrbotten,Boden,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1457,MYH 2024/997,2024,False,INSU AB,"Säkerhetsprojektering- brand-, inbrott-, kamer...",Säkerhetstjänster,95,0,0,2024,Södermanland,Nyköping,1,False
1458,MYH 2024/998,2024,True,Campus Nyköping,Hälsofrämjande och pedagogiska insatser med häst,"Lantbruk, djurvård, trädgård, skog och fiske",50,24,24,2024,Södermanland,Nyköping,1,False
1459,MYH 2024/999,2024,False,Changemaker Educations AB,Futuregames Accessible Game Design,Data/IT,25,0,0,2024,Skåne,Malmö,3,True
1460,MYH 2024/999,2024,False,Changemaker Educations AB,Futuregames Accessible Game Design,Data/IT,25,0,0,2024,Norrbotten,Boden,3,True
1461,MYH 2024/999,2024,False,Changemaker Educations AB,Futuregames Accessible Game Design,Data/IT,25,0,0,2024,Stockholm,Stockholm,3,True

In [24]:
def create_rel_kurser_alla_kommuner(con, years: list[int] | int | None = None, *, distinct=False):
    if not years:
        years = None
    elif isinstance(years, int):
        years = [years]

    rel_all = con.sql(
        """
        with kurser_alla_kommuner as (

        select
            "Diarienummer",
            "Ansökningsomgång",
            "Beslut",
            "Utbildningsanordnare",
            "Utbildningsnamn",
            "Utbildningsområde",
            "YH-poäng",
            "Beviljade platser",
            "Beviljade platser totalt",
            "Start",
            "Län",
            "Kommun",
            "Antal kommuner",
            "Flera kommuner"
        from kurser_beslut kb
        where
            "Flera kommuner" is not TRUE
            -- and kb."Ansökningsomgång" = 2024
            and ( $year IS NULL OR kb."Ansökningsomgång" = ANY($year) )
        
        union all

        select
            kb."Diarienummer",
            kb."Ansökningsomgång",
            kb."Beslut",
            kb."Utbildningsanordnare",
            kb."Utbildningsnamn",
            kb."Utbildningsområde",
            kb."YH-poäng",
            kb."Beviljade platser",
            kb."Beviljade platser totalt",
            kb."Start",
            kk."Län",                -- kurser_kommun
            kk."Kommun",             -- kurser_kommun
            kb."Antal kommuner",
            kb."Flera kommuner"
        from kurser_beslut kb
        join kurser_kommun kk
            on kk."Diarienummer" = kb."Diarienummer"
        where
            kb."Flera kommuner" is TRUE
            and ( $year IS NULL OR kb."Ansökningsomgång" = ANY($year) )

        )
        select
            -- distinct on ("Diarienummer", "Kommun")
            *
        from kurser_alla_kommuner
        order by "Diarienummer"
        ;""",
        params={"year": years},
    )

    if distinct:
        rel_distinct = con.sql(
            """
            select distinct on ("Diarienummer", "Kommun")
                "Diarienummer",
                "Ansökningsomgång",
                "Beslut",
                "Utbildningsanordnare",
                "Utbildningsnamn",
                "Utbildningsområde",
                "YH-poäng",
                -- "Beviljade platser",
                "Beviljade platser totalt",
                -- "Start",
                "Län",
                "Kommun",
                "Antal kommuner",
                "Flera kommuner"
            from rel_all
            ;"""
        )

        return rel_distinct

    return rel_all


create_rel_kurser_alla_kommuner(con, years=2024, distinct=True).df()

,Diarienummer,Ansökningsomgång,Beslut,Utbildningsanordnare,Utbildningsnamn,Utbildningsområde,YH-poäng,Beviljade platser totalt,Län,Kommun,Antal kommuner,Flera kommuner
0,MYH 2024/1000,2024,False,Changemaker Educations AB,Futuregames Accessible Game Production,Juridik,25,0,Stockholm,Stockholm,3,True
1,MYH 2024/1006,2024,False,Stiftelsen Stockholms Tekniska Institut,Infrastrukturplanering och strategi,Samhällsbyggnad och byggteknik,50,0,Stockholm,Stockholm,1,False
2,MYH 2024/1007,2024,False,Plushögskolan AB - Affärshögskolan,Hållbara inköps- och upphandlingsprocesser,"Ekonomi, administration och försäljning",45,0,Jönköping,Jönköping,5,True
3,MYH 2024/1009,2024,True,Plushögskolan AB - Affärshögskolan,Strategisk hållbarhetsutveckling,"Ekonomi, administration och försäljning",45,100,Stockholm,Stockholm,4,True
4,MYH 2024/1015,2024,False,"Västra Götalands läns landsting, Biologiska Yr...",Vattenhushållning i livsmedelsproduktionen.,"Lantbruk, djurvård, trädgård, skog och fiske",40,0,Västra Götaland,Skara,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1197,MYH 2024/968,2024,False,INSU AB,Sprinklerprojektering,Samhällsbyggnad och byggteknik,80,0,Södermanland,Katrineholm,1,False
1198,MYH 2024/976,2024,True,Folkuniversitetet - Stiftelsen Kursverksamhete...,GIS Data Mastery: Mobil Insamling och Visualis...,Samhällsbyggnad och byggteknik,30,15,Gävleborg,Gävle,1,False
1199,MYH 2024/977,2024,False,Folkuniversitetet - Stiftelsen Kursverksamhete...,GIS Essentials: Grundläggande tekniker och til...,Samhällsbyggnad och byggteknik,30,0,Gävleborg,Gävle,1,False
1200,MYH 2024/986,2024,True,IHM Business School AB Göteborg,AI-driven marknadsföring och kommunikation,"Ekonomi, administration och försäljning",40,140,Stockholm,Stockholm,1,False
1201,MYH 2024/999,2024,False,Changemaker Educations AB,Futuregames Accessible Game Design,Data/IT,25,0,Stockholm,Stockholm,3,True

In [25]:
def create_rel_kurser_alla_kommuner(con, years: list[int] | int | None = None, *, distinct=False):
    if not years:
        years = None
    elif isinstance(years, int):
        years = [years]

    base_query = """
        with kurser_alla_kommuner as (

        select
            "Diarienummer",
            "Ansökningsomgång",
            "Beslut",
            "Utbildningsanordnare",
            "Utbildningsnamn",
            "Utbildningsområde",
            "YH-poäng",
            "Beviljade platser",
            "Beviljade platser totalt",
            "Start",
            "Län",
            "Kommun",
            "Antal kommuner",
            "Flera kommuner"
        from kurser_beslut kb
        where
            "Flera kommuner" is not TRUE
            -- and kb."Ansökningsomgång" = 2024
            and ( $year IS NULL OR kb."Ansökningsomgång" = ANY($year) )
        
        union all

        select
            kb."Diarienummer",
            kb."Ansökningsomgång",
            kb."Beslut",
            kb."Utbildningsanordnare",
            kb."Utbildningsnamn",
            kb."Utbildningsområde",
            kb."YH-poäng",
            kb."Beviljade platser",
            kb."Beviljade platser totalt",
            kb."Start",
            kk."Län",                -- kurser_kommun
            kk."Kommun",             -- kurser_kommun
            kb."Antal kommuner",
            kb."Flera kommuner"
        from kurser_beslut kb
        join kurser_kommun kk
            on kk."Diarienummer" = kb."Diarienummer"
        where
            kb."Flera kommuner" is TRUE
            and ( $year IS NULL OR kb."Ansökningsomgång" = ANY($year) )

        )"""

    if distinct:
        query = (
            base_query
            + """
        select distinct on ("Diarienummer", "Kommun")
            "Diarienummer",
            "Ansökningsomgång",
            "Beslut",
            "Utbildningsanordnare",
            "Utbildningsnamn",
            "Utbildningsområde",
            "YH-poäng",
            -- "Beviljade platser",
            "Beviljade platser totalt",
            -- "Start",
            "Län",
            "Kommun",
            "Antal kommuner",
            "Flera kommuner"
        from kurser_alla_kommuner
        order by "Diarienummer";"""
        )
    else:
        query = (
            base_query
            + """
        select *
        from kurser_alla_kommuner
        order by "Diarienummer";"""
        )

    rel = con.sql(query, params={"year": years})
    return rel


create_rel_kurser_alla_kommuner(con, years=2024, distinct=True).df()

,Diarienummer,Ansökningsomgång,Beslut,Utbildningsanordnare,Utbildningsnamn,Utbildningsområde,YH-poäng,Beviljade platser totalt,Län,Kommun,Antal kommuner,Flera kommuner
0,MYH 2024/1000,2024,False,Changemaker Educations AB,Futuregames Accessible Game Production,Juridik,25,0,Stockholm,Stockholm,3,True
1,MYH 2024/1000,2024,False,Changemaker Educations AB,Futuregames Accessible Game Production,Juridik,25,0,Skåne,Malmö,3,True
2,MYH 2024/1000,2024,False,Changemaker Educations AB,Futuregames Accessible Game Production,Juridik,25,0,Norrbotten,Boden,3,True
3,MYH 2024/1001,2024,False,Changemaker Educations AB,Futuregames Inclusive Game Development,"Ekonomi, administration och försäljning",25,0,Norrbotten,Boden,3,True
4,MYH 2024/1001,2024,False,Changemaker Educations AB,Futuregames Inclusive Game Development,"Ekonomi, administration och försäljning",25,0,Skåne,Malmö,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...
1197,MYH 2024/997,2024,False,INSU AB,"Säkerhetsprojektering- brand-, inbrott-, kamer...",Säkerhetstjänster,95,0,Södermanland,Nyköping,1,False
1198,MYH 2024/998,2024,True,Campus Nyköping,Hälsofrämjande och pedagogiska insatser med häst,"Lantbruk, djurvård, trädgård, skog och fiske",50,24,Södermanland,Nyköping,1,False
1199,MYH 2024/999,2024,False,Changemaker Educations AB,Futuregames Accessible Game Design,Data/IT,25,0,Norrbotten,Boden,3,True
1200,MYH 2024/999,2024,False,Changemaker Educations AB,Futuregames Accessible Game Design,Data/IT,25,0,Stockholm,Stockholm,3,True
1201,MYH 2024/999,2024,False,Changemaker Educations AB,Futuregames Accessible Game Design,Data/IT,25,0,Skåne,Malmö,3,True

In [26]:
alla_kurser = create_rel_kurser_alla_kommuner(con, years=2024, distinct=True)

In [27]:
df_kommun_kurser_beviljade = (
    con.sql(
        """
    select
        Kommun,
        count(*) as "Kurser, antal beviljade"
    from alla_kurser
    where
        Beslut = true
        and Län = 'Stockholm'
    group by Kommun
    order by "Kurser, antal beviljade" desc, Kommun
    ;"""
    )
    .df()
    .set_index("Kommun")
)

df_kommun_kurser_beviljade  # filtered by Län

             Kurser, antal beviljade
Kommun
Stockholm                        153
Solna                             26
Globen                             4
Liljeholmen                        3
Nynäshamn                          3
Jordbro                            2
Tumba                              2
Bromma                             1
Norrtälje                          1
Södertälje                         1

In [28]:
df_lan_kurser_beviljade = (
    con.sql(
        """
    select
        Län,
        count(*) as "Kurser, antal beviljade"
    from alla_kurser
    where Beslut = true
    group by Län
    order by "Kurser, antal beviljade" desc, Län
    ;"""
    )
    .df()
    .set_index("Län")
)

df_lan_kurser_beviljade

                 Kurser, antal beviljade
Län
Stockholm                            196
Västra Götaland                      123
Skåne                                 67
Östergötland                          26
Örebro                                24
Västerbotten                          23
Västmanland                           23
Jönköping                             21
Södermanland                          20
Norrbotten                            15
Uppsala                               14
Värmland                              11
Kronoberg                             10
Gävleborg                              9
Västernorrland                         9
Blekinge                               8
Dalarna                                7
Gotland                                2
Jämtland                               2
Kalmar                                 2
Halland                                1

In [29]:
con.sql("""select * from program_beslut""").describe()

┌─────────┬───────────────────┬────────────────────────────────────────────────────────────────────┬──────────────┬──────────────┬────────────────────┬────────────────┬───────────────────┬────────────┬────────────────────┬─────────────────────────────────┬───────────────┬───────────────────────────┬───────────────────────────────┬──────────────────────┬──────────────────────────┬─────────────────────────────────────┬────────────────────┬───────────────┬─────────┐
│  aggr   │ Utbildningsområde │                          Utbildningsnamn                           │     Län      │    Kommun    │   Antal kommuner   │ Flera kommuner │     YH-poäng      │ Studieform │    Studietakt %    │      Utbildningsanordnare       │ Huvudmannatyp │ Sökta utbildningsomgångar │ Beviljade utbildningsomgångar │ Sökta platser totalt │ Beviljade platser totalt │ Sökta platser per utbildningsomgång │  Ansökningsomgång  │ Diarienummer  │ Beslut  │
│ varchar │      varchar      │                              varchar                               │   varchar    │   varchar    │       double       │    varchar     │      double       │  varchar   │       double       │             varchar             │    varchar    │          double           │            double             │        double        │          double          │               double                │       double       │    varchar    │ varchar │
├─────────┼───────────────────┼────────────────────────────────────────────────────────────────────┼──────────────┼──────────────┼────────────────────┼────────────────┼───────────────────┼────────────┼────────────────────┼─────────────────────────────────┼───────────────┼───────────────────────────┼───────────────────────────────┼──────────────────────┼──────────────────────────┼─────────────────────────────────────┼────────────────────┼───────────────┼─────────┤
│ count   │ 7640              │ 7640                                                               │ 7640         │ 7640         │             7640.0 │ 7640           │            7640.0 │ 7640       │             7640.0 │ 7640                            │ 7640          │                    7640.0 │                        7640.0 │               7640.0 │                   7640.0 │                              7640.0 │             7640.0 │ 7640          │ 7640    │
│ mean    │ NULL              │ NULL                                                               │ NULL         │ NULL         │ 1.7663612565445026 │ NULL           │ 353.5969895287958 │ NULL       │  95.12434554973822 │ NULL                            │ NULL          │        3.6657068062827225 │            0.9267015706806283 │    92.90353403141361 │       23.564659685863873 │                  25.364005235602093 │  2021.791884816754 │ NULL          │ NULL    │
│ stddev  │ NULL              │ NULL                                                               │ NULL         │ NULL         │ 1.5696907844064738 │ NULL           │ 88.82489833695931 │ NULL       │ 14.425471790646563 │ NULL                            │ NULL          │        0.9533026066420978 │             1.387626622080571 │   45.391217216730816 │       38.489291846850016 │                  10.276047854234903 │ 1.4112064740312367 │ NULL          │ NULL    │
│ min     │ Data/IT           │ \nSpecialistundersköterska med inriktning digital hälsa och teknik │ Blekinge     │ Alingsås     │                1.0 │ false          │             100.0 │ Bunden     │               50.0 │ ABF Göteborg Vuxenutbildning AB │ Kommun        │                       1.0 │                           0.0 │                  5.0 │                      0.0 │                                 2.0 │             2020.0 │ MYH 2020/1698 │ false   │
│ max     │ Övrigt            │ Återbruksstrateg                                                   │ Östergötland │ Östra Göinge │               10.0 │ true           │             999.0 │ Distans    │              100.0 │ Östsvenska Yrkeshögskolan AB    │ Statlig       │                       5.0 │                           5.0 │                175.0 │                    175.0 │                                35.0 │             2024.0 │ MYH 2024/4278 │ true    │
│ median  │ NULL              │ NULL                                                               │ NULL         │ NULL         │                1.0 │ NULL           │             400.0 │ NULL       │              100.0 │ NULL                            │ NULL          │                       3.0 │                           0.0 │                100.0 │                      0.0 │                                30.0 │             2022.0 │ NULL          │ NULL    │
└─────────┴───────────────────┴────────────────────────────────────────────────────────────────────┴──────────────┴──────────────┴────────────────────┴────────────────┴───────────────────┴────────────┴────────────────────┴─────────────────────────────────┴───────────────┴───────────────────────────┴───────────────────────────────┴──────────────────────┴──────────────────────────┴─────────────────────────────────────┴────────────────────┴───────────────┴─────────┘

In [30]:
def create_rel_program_alla_kommuner(con, years: list[int] | int | None = None, *, distinct=False):
    if not years:
        years = None
    elif isinstance(years, int):
        years = [years]

    query = """
        with program_alla_kommuner as (

        select
            "Utbildningsområde",
            "Utbildningsnamn",
            "Län",
            "Kommun",
            "Antal kommuner",
            "Flera kommuner",
            "YH-poäng",
            "Studieform",
            "Studietakt %" as "Studietakt %",
            "Utbildningsanordnare",
            "Huvudmannatyp",
            "Sökta utbildningsomgångar",
            "Beviljade utbildningsomgångar",
            "Sökta platser totalt",
            "Beviljade platser totalt",
            "Sökta platser per utbildningsomgång",
            "Ansökningsomgång",
            "Diarienummer",
            "Beslut"
        from program_beslut pb
        where
            "Flera kommuner" is not TRUE
            and ( $year IS NULL OR pb."Ansökningsomgång" = ANY($year) )
        
        union all

        select
            pb."Utbildningsområde",
            pb."Utbildningsnamn",
            pk."Län",                -- kurser_kommun
            pk."Kommun",             -- kurser_kommun
            pb."Antal kommuner",
            pb."Flera kommuner",
            pb."YH-poäng",
            pb."Studieform",
            pb."Studietakt %" as "Studietakt %",
            pb."Utbildningsanordnare",
            pb."Huvudmannatyp",
            pb."Sökta utbildningsomgångar",
            pb."Beviljade utbildningsomgångar",
            pb."Sökta platser totalt",
            pb."Beviljade platser totalt",
            pb."Sökta platser per utbildningsomgång",
            pb."Ansökningsomgång",
            pb."Diarienummer",
            pb."Beslut"
        from program_beslut pb
        join program_kommun pk
            on pk."Diarienummer" = pb."Diarienummer"
        where
            pb."Flera kommuner" is TRUE
            and ( $year IS NULL OR pb."Ansökningsomgång" = ANY($year) )

        )
        select distinct on ("Diarienummer", "Kommun")
            *
        from program_alla_kommuner
        order by "Diarienummer";"""

    rel = con.sql(query, params={"year": years})
    return rel


create_rel_program_alla_kommuner(con, years=2024).df()

,Utbildningsområde,Utbildningsnamn,Län,Kommun,Antal kommuner,Flera kommuner,YH-poäng,Studieform,Studietakt %,Utbildningsanordnare,Huvudmannatyp,Sökta utbildningsomgångar,Beviljade utbildningsomgångar,Sökta platser totalt,Beviljade platser totalt,Sökta platser per utbildningsomgång,Ansökningsomgång,Diarienummer,Beslut
0,Hälso- och sjukvård samt socialt arbete,Specialistundersköterska inom vård och omsorg ...,Örebro,Örebro,1,False,200,Distans,50,Örebro kommun Yrkesutbildningscenter,Kommun,5,2,150,60,30,2024,MYH 2024/2687,True
1,Hälso- och sjukvård samt socialt arbete,Specialistundersköterska Psykisk ohälsa/Skötare,Örebro,Örebro,1,False,235,Distans,50,Örebro kommun Yrkesutbildningscenter,Kommun,5,3,150,90,30,2024,MYH 2024/2688,True
2,Data/IT,Futuregames QA/Game Tester,Stockholm,Stockholm,3,True,300,Bunden,100,Futuregames Boden,Privat,3,0,90,0,30,2024,MYH 2024/2877,False
3,Data/IT,Futuregames QA/Game Tester,Norrbotten,Boden,3,True,300,Bunden,100,Futuregames Boden,Privat,3,0,90,0,30,2024,MYH 2024/2877,False
4,Data/IT,Futuregames QA/Game Tester,Skåne,Malmö,3,True,300,Bunden,100,Futuregames Boden,Privat,3,0,90,0,30,2024,MYH 2024/2877,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1817,Teknik och tillverkning,Automationstekniker,Stockholm,Stockholm,1,False,400,Distans,100,AVIC AB,Privat,3,0,75,0,25,2024,MYH 2024/4273,False
1818,Samhällsbyggnad och byggteknik,"Byggnadsvårdsingenjör - arbetsledning, renover...",Västerbotten,Umeå,1,False,415,Distans,100,Umeå kommun - Dragonskolan,Kommun,2,2,40,40,20,2024,MYH 2024/4274,True
1819,Samhällsbyggnad och byggteknik,Optimering av hållbara energisystem med AI-stöd,Stockholm,Stockholm,1,False,400,Distans,100,AVIC AB,Privat,4,0,104,0,26,2024,MYH 2024/4275,False
1820,Data/IT,Python-Engineer,Västra Götaland,Göteborg,1,False,400,Bunden,100,IT-Högskolan Sverige AB,Privat,3,0,105,0,35,2024,MYH 2024/4276,False
1821,Data/IT,.NET-Cloud developer,Stockholm,Stockholm,1,False,400,Bunden,100,IT-Högskolan Stockholm AB,Privat,3,0,105,0,35,2024,MYH 2024/4278,False

In [31]:
df_program_alla_kommuner = create_rel_program_alla_kommuner(con, years=2024).df()

df_program_alla_kommuner.groupby("Diarienummer")["Antal kommuner"].first().sum()

np.int64(1822)

In [32]:
rel_kurser = create_rel_kurser_alla_kommuner(con, distinct=True)

In [33]:
con.sql(
    """
    select
        Utbildningsanordnare,
        Utbildningsnamn,
        count(distinct Kommun) as "Kommuner",
        count(distinct Län) as "Län"
    from rel_kurser
    group by Utbildningsanordnare, Utbildningsnamn
    order by Utbildningsanordnare, Utbildningsnamn
    ;"""
)

┌──────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────┬──────────┬───────┐
│             Utbildningsanordnare             │                                        Utbildningsnamn                                        │ Kommuner │  Län  │
│                   varchar                    │                                            varchar                                            │  int64   │ int64 │
├──────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┼──────────┼───────┤
│ ABF Göteborg Vuxenutbildning AB              │ AI i utbildning                                                                               │        1 │     1 │
│ ABF Göteborg Vuxenutbildning AB              │ Design av digital didaktik                                                                    │        1 │     1 │
│ ABF Göteborg Vuxenutbildning AB              │ Förskolan i ett digitalt samhälle                                                             │        1 │     1 │
│ ABF Göteborg Vuxenutbildning AB              │ Generativ AI som ett verktyg i undervisningen                                                 │        1 │     1 │
│ ABF Göteborg Vuxenutbildning AB              │ Generativ AI-teknik: historia, nutid och framtid i pedagogiska sammanhang                     │        1 │     1 │
│ ABF Göteborg Vuxenutbildning AB              │ Naturvetenskap och teknik i förskolan                                                         │        1 │     1 │
│ ABF Göteborg Vuxenutbildning AB              │ Tillämpning av generativ AI i pedagogisk planering                                            │        1 │     1 │
│ AGSTU AB                                     │ FPGA Systemkonstruktion med VHDL                                                              │        1 │     1 │
│ AGSTU AB                                     │ Högnivåsyntes med C för FPGA                                                                  │        1 │     1 │
│ AGSTU AB                                     │ Introduktion till FPGA och VHDL-programmering                                                 │        1 │     1 │
│    ·                                         │           ·                                                                                   │        · │     · │
│    ·                                         │           ·                                                                                   │        · │     · │
│    ·                                         │           ·                                                                                   │        · │     · │
│ Yrkesutbildaren Habo AB                      │ Projektledare inom El                                                                         │        1 │     1 │
│ Älmhults kommun, Haganässkolan               │ Livscykelanalys för förpackningsindustrin - Life Cycle Assessment for the packaging industry. │        1 │     1 │
│ Åsbro Kursgård AB                            │ Linjebyggnad transmissionsnät                                                                 │        1 │     1 │
│ Åsbro Kursgård AB                            │ Reservkraft för säkrad elförsörjning                                                          │        1 │     1 │
│ Åsbro Kursgård AB                            │ Riskhantering av induktion vid högspänningsanläggningar                                       │        1 │     1 │
│ Östsvenska Yrkeshögskolan AB                 │ Florist fördjupning                                                                           │        1 │     1 │
│ Östsvenska Yrkeshögskolan AB                 │ Hållbara transporter                                                                          │        1 │     1 │
│ Östsvenska Yrkeshögskolan AB                 │ Påbyggnad beskärning och växtvård                                                             │        1 │     1 │
│ Östsvenska Yrkeshögskolan AB                 │ Påbyggnad växtkunskap för offentlig miljö                                                     │        1 │     1 │
│ Östsvenska Yrkeshögskolan AB                 │ Sakkunnig inom tull                                                                           │        1 │     1 │
├──────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────┴──────────┴───────┤
│ 877 rows (20 shown)                                                                                                                                   4 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [34]:
con.sql(
    """
select
    Utbildningsanordnare,
    count(distinct Kommun) as "Kommuner, antal",
    count(distinct Län) as "Län, antal",
    count(distinct Diarienummer) as "Kurser, antal",
    round(mean("YH-poäng"),0)::integer as "YH-poäng, medelvärde"
from rel_kurser
group by Utbildningsanordnare
order by (count(distinct Kommun) + count(distinct Län)) desc, Utbildningsanordnare

    ;"""
)

┌───────────────────────────────────────────────────────────────────────────┬─────────────────┬────────────┬───────────────┬──────────────────────┐
│                           Utbildningsanordnare                            │ Kommuner, antal │ Län, antal │ Kurser, antal │ YH-poäng, medelvärde │
│                                  varchar                                  │      int64      │   int64    │     int64     │        int32         │
├───────────────────────────────────────────────────────────────────────────┼─────────────────┼────────────┼───────────────┼──────────────────────┤
│ YH Akademin AB                                                            │              31 │         15 │            45 │                   44 │
│ Amsac AB                                                                  │              29 │         12 │            19 │                   47 │
│ Plushögskolan AB - Vårdyrkeshögskolan                                     │              19 │         15 │             9 │                   46 │
│ Folkuniversitetet - Stiftelsen Kursverksamheten vid Uppsala universitetet │              15 │         12 │            15 │                   39 │
│ Technigo AB                                                               │              10 │          9 │             9 │                   42 │
│ Ja&Ja AB                                                                  │              12 │          5 │             4 │                   60 │
│ Plushögskolan AB - Affärshögskolan                                        │               9 │          8 │             4 │                   40 │
│ Movant AB                                                                 │               9 │          7 │             5 │                   52 │
│ Plushögskolan AB - Teknikhögskolan                                        │               9 │          7 │             7 │                   46 │
│ TUC Sweden AB - Yrkeshögskola                                             │               7 │          5 │            18 │                   40 │
│               ·                                                           │               · │          · │             · │                    · │
│               ·                                                           │               · │          · │             · │                    · │
│               ·                                                           │               · │          · │             · │                    · │
│ Vilhelmina kommun, Vilhelmina Lärcentrum                                  │               1 │          1 │             2 │                   45 │
│ Värna                                                                     │               1 │          1 │             1 │                   80 │
│ Västerås Stad/Barn- och Utbildningsförvaltningen/Västerås Yrkeshögskola   │               1 │          1 │             4 │                   76 │
│ WeWon Media Group AB                                                      │               1 │          1 │             5 │                   45 │
│ XeDrix AB                                                                 │               1 │          1 │             3 │                   57 │
│ Xenter Yrkeshögskola                                                      │               1 │          1 │            11 │                   35 │
│ Yrkeshögskola Campus Mölndal                                              │               1 │          1 │             3 │                   33 │
│ Yrkesutbildaren Habo AB                                                   │               1 │          1 │             7 │                   84 │
│ Älmhults kommun, Haganässkolan                                            │               1 │          1 │             1 │                   40 │
│ Östsvenska Yrkeshögskolan AB                                              │               1 │          1 │             5 │                   43 │
├───────────────────────────────────────────────────────────────────────────┴─────────────────┴────────────┴───────────────┴──────────────────────┤
│ 166 rows (20 shown)                                                                                                                   5 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [35]:
con.sql(
    """
select
    Utbildningsområde,
    count(distinct "Diarienummer") as d,
    (
        select
            Utbildningsnamn
        from rel_kurser rk2
        where
            rk2.Utbildningsområde = rk1.Utbildningsområde
        group by Utbildningsnamn
        order by count(*) desc
        limit 1
    ) as b
from rel_kurser rk1
group by Utbildningsområde
order by d desc
    ;"""
)

┌──────────────────────────────────────────────┬───────┬──────────────────────────────────────────────────────────────────────────────────┐
│              Utbildningsområde               │   d   │                                        b                                         │
│                   varchar                    │ int64 │                                     varchar                                      │
├──────────────────────────────────────────────┼───────┼──────────────────────────────────────────────────────────────────────────────────┤
│ Ekonomi, administration och försäljning      │   221 │ Cirkulära mötesplatser som affärs- och verksamhetsutveckling                     │
│ Data/IT                                      │   157 │ TypeScript                                                                       │
│ Teknik och tillverkning                      │   121 │ Digitalisering och automation i hållbar produktion                               │
│ Hälso- och sjukvård samt socialt arbete      │   109 │ Psykisk ohälsa hos äldre                                                         │
│ Samhällsbyggnad och byggteknik               │   105 │ Ventilation Mätning/Injustering                                                  │
│ Lantbruk, djurvård, trädgård, skog och fiske │    38 │ Markbyggnad, anläggning och kalkylering - park och trädgård                      │
│ Pedagogik och undervisning                   │    30 │ Funktionsnedsättning/Funktionsvariation hos barn och unga                        │
│ Hotell, restaurang och turism                │    24 │ Food & Beverage Management Executive                                             │
│ Säkerhetstjänster                            │    19 │ Samordning inom skolsäkerhetsarbetet                                             │
│ Juridik                                      │    18 │ Trygg AI i praktiken                                                             │
│ Kultur, media och design                     │    18 │ Digitala och Hybrida användarupplevelser inom Musei- och Kulturarvsverksamheter  │
│ Journalistik och information                 │    14 │ Digital propaganda                                                               │
│ Transporttjänster                            │     4 │ Eco Driving som verktyg för minskad klimatpåverkan i transportbranschen          │
│ Friskvård och kroppsvård                     │     2 │ Lic. Evidensbaserad Personlig Tränare (All-inclusive)                            │
├──────────────────────────────────────────────┴───────┴──────────────────────────────────────────────────────────────────────────────────┤
│ 14 rows                                                                                                                       3 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [36]:
con.sql(
    """
        select
            Utbildningsnamn,
            count(*) as c
        from rel_kurser rk2
        group by Utbildningsnamn
        order by c desc
    ;"""
)

┌────────────────────────────────────────────────────────────────────────┬───────┐
│                            Utbildningsnamn                             │   c   │
│                                varchar                                 │ int64 │
├────────────────────────────────────────────────────────────────────────┼───────┤
│ Psykisk ohälsa hos äldre                                               │     8 │
│ Palliativ vård                                                         │     7 │
│ Välfärdsteknik inom vård och omsorg                                    │     7 │
│ TypeScript                                                             │     6 │
│ Missbruk och beroende                                                  │     6 │
│ Mikrobiologi och vårdhygien                                            │     6 │
│ Våld i nära relation                                                   │     5 │
│ Tillämpning av GIS för krisanalyser och samordning                     │     5 │
│ Symtomlindring palliativ vård                                          │     5 │
│ Ventilation Mätning/Injustering                                        │     5 │
│                ·                                                       │     · │
│                ·                                                       │     · │
│                ·                                                       │     · │
│ AI för säljare och marknadskommunikatörer                              │     1 │
│ Välfärdsteknik och digitala verktyg                                    │     1 │
│ Demenssjukdomar                                                        │     1 │
│ Processledning inom jämställdhet och jämlikhet                         │     1 │
│ Samordning och strategiarbete inom elektrifiering för grön omställning │     1 │
│ Omvårdnad vid psykisk ohälsa hos äldre                                 │     1 │
│ Digital teknik i fastighetsförvaltningen                               │     1 │
│ Neuropsykiatriska diagnoser, bemötande, arbetssätt och metoder         │     1 │
│ Cloud Fundamentals                                                     │     1 │
│ Invasiva växter i utemiljöer                                           │     1 │
├────────────────────────────────────────────────────────────────────────┴───────┤
│ 849 rows (20 shown)                                                  2 columns │
└────────────────────────────────────────────────────────────────────────────────┘

In [37]:
con.sql(
        """
    select
        Utbildningsområde,
        count(distinct case when Beslut = TRUE then Diarienummer end)::integer as Beviljade,
        count(distinct case when Beslut = FALSE then Diarienummer end)::integer as Avslag,
        abs(Beviljade - Avslag) as diff_beslut
    from rel_kurser
    where
        Ansökningsomgång = 2024
    group by Utbildningsområde
    order by (Beviljade + Avslag) desc, Utbildningsområde
    ;"""
    )

┌──────────────────────────────────────────────┬───────────┬────────┬─────────────┐
│              Utbildningsområde               │ Beviljade │ Avslag │ diff_beslut │
│                   varchar                    │   int32   │ int32  │    int32    │
├──────────────────────────────────────────────┼───────────┼────────┼─────────────┤
│ Ekonomi, administration och försäljning      │       109 │    112 │           3 │
│ Data/IT                                      │        73 │     84 │          11 │
│ Teknik och tillverkning                      │        70 │     51 │          19 │
│ Hälso- och sjukvård samt socialt arbete      │        56 │     53 │           3 │
│ Samhällsbyggnad och byggteknik               │        64 │     41 │          23 │
│ Lantbruk, djurvård, trädgård, skog och fiske │        14 │     24 │          10 │
│ Pedagogik och undervisning                   │        12 │     18 │           6 │
│ Hotell, restaurang och turism                │        15 │      9 │           6 │
│ Säkerhetstjänster                            │         8 │     11 │           3 │
│ Juridik                                      │         9 │      9 │           0 │
│ Kultur, media och design                     │         9 │      9 │           0 │
│ Journalistik och information                 │         9 │      5 │           4 │
│ Transporttjänster                            │         3 │      1 │           2 │
│ Friskvård och kroppsvård                     │         0 │      2 │           2 │
├──────────────────────────────────────────────┴───────────┴────────┴─────────────┤
│ 14 rows                                                               4 columns │
└─────────────────────────────────────────────────────────────────────────────────┘

In [38]:
con.sql(
        """
    select distinct
        Diarienummer,
        Utbildningsnamn,
        Utbildningsområde,
        Beslut
    from rel_kurser
    where
        Ansökningsomgång = 2024
        and Beslut = true
    ;"""
    )

┌───────────────┬──────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────┬─────────┐
│ Diarienummer  │                                     Utbildningsnamn                                      │            Utbildningsområde            │ Beslut  │
│    varchar    │                                         varchar                                          │                 varchar                 │ boolean │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────┼─────────┤
│ MYH 2024/1040 │ Prompt Engineering och generativ AI för utvecklare                                       │ Data/IT                                 │ true    │
│ MYH 2024/1042 │ Robotic Process Automation                                                               │ Data/IT                                 │ true    │
│ MYH 2024/1047 │ UX-writing                                                                               │ Journalistik och information            │ true    │
│ MYH 2024/1050 │ CAD för VVS                                                                              │ Samhällsbyggnad och byggteknik          │ true    │
│ MYH 2024/1057 │ Hållbar byggprojektering med BIM                                                         │ Samhällsbyggnad och byggteknik          │ true    │
│ MYH 2024/1077 │ Byggnadsfysik inom träbyggnation                                                         │ Samhällsbyggnad och byggteknik          │ true    │
│ MYH 2024/1080 │ Cybersäkerhet i elkraftsystem                                                            │ Data/IT                                 │ true    │
│ MYH 2024/1081 │ Sustainable Supply Chain Transformation                                                  │ Ekonomi, administration och försäljning │ true    │
│ MYH 2024/1085 │ Digitalisering och automation i hållbar produktion                                       │ Teknik och tillverkning                 │ true    │
│ MYH 2024/1105 │ Ellagring, stödtjänster och produktionsreglering av vattenkraft, vindkraft och solceller │ Teknik och tillverkning                 │ true    │
│      ·        │           ·                                                                              │    ·                                    │  ·      │
│      ·        │           ·                                                                              │    ·                                    │  ·      │
│      ·        │           ·                                                                              │    ·                                    │  ·      │
│ MYH 2024/909  │ Cloud Native Computing                                                                   │ Data/IT                                 │ true    │
│ MYH 2024/912  │ Customer Experience Management                                                           │ Ekonomi, administration och försäljning │ true    │
│ MYH 2024/944  │ Högnivåsyntes med C för FPGA                                                             │ Data/IT                                 │ true    │
│ MYH 2024/954  │ Markexploatering och fördjupad entreprenadjuridik                                        │ Samhällsbyggnad och byggteknik          │ true    │
│ MYH 2024/970  │ Ventilationsinjustering                                                                  │ Samhällsbyggnad och byggteknik          │ true    │
│ MYH 2024/974  │ Säkerhetsskyddssamordning                                                                │ Säkerhetstjänster                       │ true    │
│ MYH 2024/979  │ Ledning och samordning av informations- och cybersäkerhet                                │ Säkerhetstjänster                       │ true    │
│ MYH 2024/981  │ Introduktion till FPGA och VHDL-programmering                                            │ Teknik och tillverkning                 │ true    │
│ MYH 2024/993  │ Solenergiprojektering                                                                    │ Samhällsbyggnad och byggteknik          │ true    │
│ MYH 2024/994  │ Att bygga en informationssäkerhetskultur                                                 │ Säkerhetstjänster                       │ true    │
├───────────────┴──────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────┴─────────┤
│ 451 rows (20 shown)                                                                                                                                4 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [39]:
con.sql(
        """
    select distinct
        count(Diarienummer),
        count(Utbildningsnamn),
        Utbildningsområde,
        count(Beslut)
    from rel_kurser
    where
        Ansökningsomgång = 2024
        and Beslut = true
    group by
        Utbildningsområde
    order by count(Beslut) desc
    ;"""
    )

┌─────────────────────┬────────────────────────┬──────────────────────────────────────────────┬───────────────┐
│ count(Diarienummer) │ count(Utbildningsnamn) │              Utbildningsområde               │ count(Beslut) │
│        int64        │         int64          │                   varchar                    │     int64     │
├─────────────────────┼────────────────────────┼──────────────────────────────────────────────┼───────────────┤
│                 132 │                    132 │ Ekonomi, administration och försäljning      │           132 │
│                 109 │                    109 │ Hälso- och sjukvård samt socialt arbete      │           109 │
│                 106 │                    106 │ Teknik och tillverkning                      │           106 │
│                  87 │                     87 │ Data/IT                                      │            87 │
│                  76 │                     76 │ Samhällsbyggnad och byggteknik               │            76 │
│                  24 │                     24 │ Hotell, restaurang och turism                │            24 │
│                  18 │                     18 │ Lantbruk, djurvård, trädgård, skog och fiske │            18 │
│                  14 │                     14 │ Pedagogik och undervisning                   │            14 │
│                  11 │                     11 │ Journalistik och information                 │            11 │
│                  10 │                     10 │ Säkerhetstjänster                            │            10 │
│                  10 │                     10 │ Kultur, media och design                     │            10 │
│                  10 │                     10 │ Juridik                                      │            10 │
│                   6 │                      6 │ Transporttjänster                            │             6 │
├─────────────────────┴────────────────────────┴──────────────────────────────────────────────┴───────────────┤
│ 13 rows                                                                                           4 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [40]:
con.sql(
        """
        with unique_entries as (
            select distinct Diarienummer, Utbildningsnamn, Utbildningsområde, Beslut
            from rel_kurser
            where
                Ansökningsomgång = 2024
                -- and Beslut = true
        )
        select
            Utbildningsområde,
            count(Beslut)
        from unique_entries
        group by
            Utbildningsområde
        order by count(Beslut) desc

    ;"""
    )

┌──────────────────────────────────────────────┬───────────────┐
│              Utbildningsområde               │ count(Beslut) │
│                   varchar                    │     int64     │
├──────────────────────────────────────────────┼───────────────┤
│ Ekonomi, administration och försäljning      │           221 │
│ Data/IT                                      │           157 │
│ Teknik och tillverkning                      │           121 │
│ Hälso- och sjukvård samt socialt arbete      │           109 │
│ Samhällsbyggnad och byggteknik               │           105 │
│ Lantbruk, djurvård, trädgård, skog och fiske │            38 │
│ Pedagogik och undervisning                   │            30 │
│ Hotell, restaurang och turism                │            24 │
│ Säkerhetstjänster                            │            19 │
│ Juridik                                      │            18 │
│ Kultur, media och design                     │            18 │
│ Journalistik och information                 │            14 │
│ Transporttjänster                            │             4 │
│ Friskvård och kroppsvård                     │             2 │
├──────────────────────────────────────────────┴───────────────┤
│ 14 rows                                            2 columns │
└──────────────────────────────────────────────────────────────┘

In [41]:
con.sql(
    """
    select
        Utbildningsområde,
        count(Beslut)
    from
        (
        select distinct on (Diarienummer) *
        from rel_kurser
        where
            Ansökningsomgång = 2024
        ) as unique_entries
    group by
        Utbildningsområde
    order by count(Beslut) desc
    ;"""
    )

┌──────────────────────────────────────────────┬───────────────┐
│              Utbildningsområde               │ count(Beslut) │
│                   varchar                    │     int64     │
├──────────────────────────────────────────────┼───────────────┤
│ Ekonomi, administration och försäljning      │           221 │
│ Data/IT                                      │           157 │
│ Teknik och tillverkning                      │           121 │
│ Hälso- och sjukvård samt socialt arbete      │           109 │
│ Samhällsbyggnad och byggteknik               │           105 │
│ Lantbruk, djurvård, trädgård, skog och fiske │            38 │
│ Pedagogik och undervisning                   │            30 │
│ Hotell, restaurang och turism                │            24 │
│ Säkerhetstjänster                            │            19 │
│ Juridik                                      │            18 │
│ Kultur, media och design                     │            18 │
│ Journalistik och information                 │            14 │
│ Transporttjänster                            │             4 │
│ Friskvård och kroppsvård                     │             2 │
├──────────────────────────────────────────────┴───────────────┤
│ 14 rows                                            2 columns │
└──────────────────────────────────────────────────────────────┘

In [42]:
con.sql(
    """
    select
        Utbildningsområde,
        count(distinct case when Beslut = TRUE then Diarienummer end)::integer as Beviljade,
        count(distinct case when Beslut = FALSE then Diarienummer end)::integer as Avslag
    from ( select distinct on (Diarienummer) * from rel_kurser ) as unique_entries
    group by
        Utbildningsområde
    order by count(Beslut) desc
    ;"""
    )

┌──────────────────────────────────────────────┬───────────┬────────┐
│              Utbildningsområde               │ Beviljade │ Avslag │
│                   varchar                    │   int32   │ int32  │
├──────────────────────────────────────────────┼───────────┼────────┤
│ Ekonomi, administration och försäljning      │       109 │    112 │
│ Data/IT                                      │        73 │     84 │
│ Teknik och tillverkning                      │        70 │     51 │
│ Hälso- och sjukvård samt socialt arbete      │        56 │     53 │
│ Samhällsbyggnad och byggteknik               │        64 │     41 │
│ Lantbruk, djurvård, trädgård, skog och fiske │        14 │     24 │
│ Pedagogik och undervisning                   │        12 │     18 │
│ Hotell, restaurang och turism                │        15 │      9 │
│ Säkerhetstjänster                            │         8 │     11 │
│ Kultur, media och design                     │         9 │      9 │
│ Juridik                                      │         9 │      9 │
│ Journalistik och information                 │         9 │      5 │
│ Transporttjänster                            │         3 │      1 │
│ Friskvård och kroppsvård                     │         0 │      2 │
├──────────────────────────────────────────────┴───────────┴────────┤
│ 14 rows                                                 3 columns │
└───────────────────────────────────────────────────────────────────┘

In [43]:
def create_rel_utbildningsomrade_beslut(con):
    rel =con.sql(
    """
    select
        Utbildningsområde,
        count(distinct case when Beslut = TRUE then Diarienummer end)::integer as Beviljade,
        count(distinct case when Beslut = FALSE then Diarienummer end)::integer as Avslag
    from ( select distinct on (Diarienummer) * from rel_kurser ) as unique_entries
    group by
        Utbildningsområde
    order by count(Beslut) desc
    ;""")
    return rel

In [44]:
rel_program_alla_kommuner = create_rel_program_alla_kommuner(con, years=2024, distinct=True)
rel_program_alla_kommuner

┌─────────────────────────────────────────┬────────────────────────────────────────────────────────────────┬─────────────────┬────────────┬────────────────┬────────────────┬──────────┬────────────┬──────────────┬──────────────────────────────────────┬───────────────┬───────────────────────────┬───────────────────────────────┬──────────────────────┬──────────────────────────┬─────────────────────────────────────┬──────────────────┬───────────────┬─────────┐
│            Utbildningsområde            │                        Utbildningsnamn                         │       Län       │   Kommun   │ Antal kommuner │ Flera kommuner │ YH-poäng │ Studieform │ Studietakt % │         Utbildningsanordnare         │ Huvudmannatyp │ Sökta utbildningsomgångar │ Beviljade utbildningsomgångar │ Sökta platser totalt │ Beviljade platser totalt │ Sökta platser per utbildningsomgång │ Ansökningsomgång │ Diarienummer  │ Beslut  │
│                 varchar                 │                            varchar                             │     varchar     │  varchar   │     int64      │    boolean     │  int64   │  varchar   │    int64     │               varchar                │    varchar    │           int64           │             int64             │        int64         │          int64           │                int64                │      int64       │    varchar    │ boolean │
├─────────────────────────────────────────┼────────────────────────────────────────────────────────────────┼─────────────────┼────────────┼────────────────┼────────────────┼──────────┼────────────┼──────────────┼──────────────────────────────────────┼───────────────┼───────────────────────────┼───────────────────────────────┼──────────────────────┼──────────────────────────┼─────────────────────────────────────┼──────────────────┼───────────────┼─────────┤
│ Hälso- och sjukvård samt socialt arbete │ Specialistundersköterska inom vård och omsorg av äldre         │ Örebro          │ Örebro     │              1 │ false          │      200 │ Distans    │           50 │ Örebro kommun Yrkesutbildningscenter │ Kommun        │                         5 │                             2 │                  150 │                       60 │                                  30 │             2024 │ MYH 2024/2687 │ true    │
│ Hälso- och sjukvård samt socialt arbete │ Specialistundersköterska Psykisk ohälsa/Skötare                │ Örebro          │ Örebro     │              1 │ false          │      235 │ Distans    │           50 │ Örebro kommun Yrkesutbildningscenter │ Kommun        │                         5 │                             3 │                  150 │                       90 │                                  30 │             2024 │ MYH 2024/2688 │ true    │
│ Data/IT                                 │ Futuregames QA/Game Tester                                     │ Norrbotten      │ Boden      │              3 │ true           │      300 │ Bunden     │          100 │ Futuregames Boden                    │ Privat        │                         3 │                             0 │                   90 │                        0 │                                  30 │             2024 │ MYH 2024/2877 │ false   │
│ Data/IT                                 │ Futuregames QA/Game Tester                                     │ Skåne           │ Malmö      │              3 │ true           │      300 │ Bunden     │          100 │ Futuregames Boden                    │ Privat        │                         3 │                             0 │                   90 │                        0 │                                  30 │             2024 │ MYH 2024/2877 │ false   │
│ Data/IT                                 │ Futuregames QA/Game Tester                                     │ Stockholm       │ Stockholm  │              3 │ true           │      300 │ Bunden     │          100 │ Futuregames Boden                    │ Privat        │                         3 │                             0 │                   90 │                        0 │                                  30 │             2024 │ MYH 2024/2877 │ false   │
│ Data/IT                                 │ Futuregames Project Manager IT & Games                         │ Västerbotten    │ Umeå       │              3 │ true           │      300 │ Distans    │          100 │ Futuregames Umeå                     │ Privat        │                         3 │                             0 │                   90 │                        0 │                                  30 │             2024 │ MYH 2024/2878 │ false   │
│ Data/IT                                 │ Futuregames Project Manager IT & Games                         │ Norrbotten      │ Boden      │              3 │ true           │      300 │ Distans    │          100 │ Futuregames Umeå                     │ Privat        │                         3 │                             0 │                   90 │                        0 │                                  30 │             2024 │ MYH 2024/2878 │ false   │
│ Data/IT                                 │ Futuregames Project Manager IT & Games                         │ Värmland        │ Karlstad   │              3 │ true           │      300 │ Distans    │          100 │ Futuregames Umeå                     │ Privat        │                         3 │                             0 │                   90 │                        0 │                                  30 │             2024 │ MYH 2024/2878 │ false   │
│ Kultur, media och design                │ Futuregames Game Artist Specialization 1                       │ Västerbotten    │ Skellefteå │              3 │ true           │      550 │ Bunden     │          100 │ Futuregames Boden                    │ Privat        │                         3 │                             0 │                   90 │                        0 │                                  30 │             2024 │ MYH 2024/2909 │ false   │
│ Kultur, media och design                │ Futuregames Game Artist Specialization 1                       │ Norrbotten      │ Boden      │              3 │ true           │      550 │ Bunden     │          100 │ Futuregames Boden                    │ Privat        │                         3 │                             0 │                   90 │                        0 │                                  30 │             2024 │ MYH 2024/2909 │ false   │
│    ·                                    │                    ·                                           │     ·           │   ·        │              · │  ·             │       ·  │   ·        │           ·  │      ·                               │   ·           │                         · │                             · │                    · │                        · │                                   · │               ·  │       ·       │   ·     │
│    ·                                    │                    ·                                           │     ·           │   ·        │              · │  ·             │       ·  │   ·        │           ·  │      ·                               │   ·           │                         · │                             · │                    · │                        · │                                   · │               ·  │       ·       │   ·     │
│    ·                                    │                    ·                                           │     ·           │   ·        │              · │  ·             │       ·  │   ·        │           ·  │      ·                               │   ·           │                         · │                             · │                    · │                        · │                                   · │               ·  │       ·       │   ·     │
│ Data/IT                                 │ Systemutvecklare av säkerhetskritiska system                   │ Östergötland    │ Linköping  │              3 │ true           │      440 │ Bunden     │          100 │ Edugrade AB                          │ Privat        │                         4 │                             0 │                  140 │                        0 │                                  35 │             2024 │ MYH 2024/4269 │ false   │
│ Data/IT                                 │ Systemutvecklare av säkerhetskritiska system                   │ Stockholm       │ Stockholm  │              1 │ false          │      440 │ Distans    │          100 │ Edugrade AB                          │ Privat        │                         4 │                             0 │                  140 │                        0 │                                  35 │             2024 │ MYH 2024/4270 │ false   │
│ Samhällsbyggnad och byggteknik          │ VA-ingenjör med AI-kompetens                                   │ Stockholm       │ Stockholm  │              2 │ true           │      425 │ Distans    │          100 │ Ai Högskolan Sverige AB              │ Privat        │                         3 │                             0 │                   90 │                        0 │                                  30 │             2024 │ MYH 2024/4271 │ false   │
│ Samhällsbyggnad och byggteknik          │ VA-ingenjör med AI-kompetens                                   │ Västra Götaland │ Göteborg   │              2 │ true           │      425 │ Distans    │          100 │ Ai Högskolan Sverige AB              │ Privat        │                         3 │                             0 │                   90 │                        0 │                                  30 │             2024 │ MYH 2024/4271 │ false   │
│ Teknik och tillverkning                 │ Drifttekniker - Kraft och värme                                │ Stockholm       │ Södertälje │              1 │ false          │      425 │ Bunden     │          100 │ Södertälje kommun, Campus Telge      │ Kommun        │                         3 │                             0 │                   60 │                        0 │                                  20 │             2024 │ MYH 2024/4272 │ false   │
│ Teknik och tillverkning                 │ Automationstekniker                                            │ Stockholm       │ Stockholm  │              1 │ false          │      400 │ Distans    │          100 │ AVIC AB                              │ Privat        │                         3 │                             0 │                   75 │                        0 │                                  25 │             2024 │ MYH 2024/4273 │ false   │
│ Samhällsbyggnad och byggteknik          │ Byggnadsvårdsingenjör - arbetsledning, renovering och återbruk │ Västerbotten    │ Umeå       │              1 │ false          │      415 │ Distans    │          100 │ Umeå kommun - Dragonskolan           │ Kommun        │                         2 │                             2 │                   40 │                       40 │                                  20 │             2024 │ MYH 2024/4274 │ true    │
│ Samhällsbyggnad och byggteknik          │ Optimering av hållbara energisystem med AI-stöd                │ Stockholm       │ Stockholm  │              1 │ false          │      400 │ Distans    │          100 │ AVIC AB                              │ Privat        │                         4 │                             0 │                  104 │                        0 │                                  26 │             2024 │ MYH 2024/4275 │ false   │
│ Data/IT                                 │ Python-Engineer                                                │ Västra Götaland │ Göteborg   │              1 │ false          │      400 │ Bunden     │          100 │ IT-Högskolan Sverige AB              │ Privat        │                         3 │                             0 │                  105 │                        0 │                                  35 │             2024 │ MYH 2024/4276 │ false   │
│ Data/IT                                 │ .NET-Cloud developer                                           │ Stockholm       │ Stockholm  │              1 │ false          │      400 │ Bunden     │          100 │ IT-Högskolan Stockholm AB            │ Privat        │                         3 │                             0 │                  105 │                        0 │                                  35 │             2024 │ MYH 2024/4278 │ false   │
├─────────────────────────────────────────┴────────────────────────────────────────────────────────────────┴─────────────────┴────────────┴────────────────┴────────────────┴──────────┴────────────┴──────────────┴──────────────────────────────────────┴───────────────┴───────────────────────────┴───────────────────────────────┴──────────────────────┴──────────────────────────┴─────────────────────────────────────┴──────────────────┴───────────────┴─────────┤
│ 1822 rows (20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                          19 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [45]:
con.sql(
    """
select
Utbildningsanordnare,
count(*) as "Antal ansökningar",
count(case when Beslut = true then 1 else 0 end),
count(distinct case when Beslut = TRUE then Diarienummer end)::integer as Beviljade,
-- round(100.00 * sum(case when Beslut = true then 1 else 0 end) / sum(case when Beslut = false then 1 else 0 end),1) as "Beviljade %",
-- round(mean("YH-poäng"),0)::integer as "YH-poäng, medelvärde"
from rel_program_alla_kommuner
where Ansökningsomgång = 2024
group by Utbildningsanordnare
-- order by c desc
"""
)

┌───────────────────────────────────────────────────────────────────────────┬───────────────────┬─────────────────────────────────────────────────────────────────────────┬───────────┐
│                           Utbildningsanordnare                            │ Antal ansökningar │ count(CASE  WHEN ((Beslut = CAST('t' AS BOOLEAN))) THEN (1) ELSE 0 END) │ Beviljade │
│                                  varchar                                  │       int64       │                                  int64                                  │   int32   │
├───────────────────────────────────────────────────────────────────────────┼───────────────────┼─────────────────────────────────────────────────────────────────────────┼───────────┤
│ Sigtuna Kommun, Centrum för vuxenutveckling                               │                 1 │                                                                       1 │         0 │
│ YH Akademin AB                                                            │                89 │                                                                      89 │        17 │
│ Futuregames Malmö                                                         │                11 │                                                                      11 │         0 │
│ Folkuniversitetet - Stiftelsen Kursverksamheten vid Uppsala universitetet │                44 │                                                                      44 │         3 │
│ KompetensUtvecklingsInstitutet Sverige AB                                 │                23 │                                                                      23 │         3 │
│ IHM Business School AB Malmö                                              │                 7 │                                                                       7 │         1 │
│ Campus Ängelholm AB                                                       │                 1 │                                                                       1 │         0 │
│ EC Utbildning AB Stockholm                                                │                 9 │                                                                       9 │         0 │
│ EC Utbildning AB Halmstad                                                 │                 2 │                                                                       2 │         0 │
│ Näringslivsakademin                                                       │                 5 │                                                                       5 │         1 │
│          ·                                                                │                 · │                                                                       · │         · │
│          ·                                                                │                 · │                                                                       · │         · │
│          ·                                                                │                 · │                                                                       · │         · │
│ Yrkeshögskolan Malmö stad                                                 │                 1 │                                                                       1 │         1 │
│ Östra Grevie Folkhögskoleförening                                         │                 1 │                                                                       1 │         0 │
│ Stockholms stad, Frans Schartaus Handelsinstitut                          │                 8 │                                                                       8 │         7 │
│ Medieinstitutet i Sverige AB                                              │                32 │                                                                      32 │        10 │
│ ProTrain Utbildning AB                                                    │                 3 │                                                                       3 │         2 │
│ Folktandvården Västra Götalandsregionen, Tandsköterskeutbildningen        │                 1 │                                                                       1 │         0 │
│ TCC Sverige AB                                                            │                 5 │                                                                       5 │         3 │
│ Blue Peak AB                                                              │                 3 │                                                                       3 │         0 │
│ Origo Academy                                                             │                 4 │                                                                       4 │         1 │
│ Campus Åre/Åre kommun                                                     │                 1 │                                                                       1 │         0 │
├───────────────────────────────────────────────────────────────────────────┴───────────────────┴─────────────────────────────────────────────────────────────────────────┴───────────┤
│ 250 rows (20 shown)                                                                                                                                                       4 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [46]:
con.sql(
    """
select * from rel_kurser
"""
)

┌───────────────┬──────────────────┬─────────┬─────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────┬──────────┬──────────────────────────┬──────────────┬───────────┬────────────────┬────────────────┐
│ Diarienummer  │ Ansökningsomgång │ Beslut  │          Utbildningsanordnare           │                             Utbildningsnamn                              │              Utbildningsområde               │ YH-poäng │ Beviljade platser totalt │     Län      │  Kommun   │ Antal kommuner │ Flera kommuner │
│    varchar    │      int64       │ boolean │                 varchar                 │                                 varchar                                  │                   varchar                    │  int64   │          int64           │   varchar    │  varchar  │     int64      │    boolean     │
├───────────────┼──────────────────┼─────────┼─────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────┼──────────────────────────┼──────────────┼───────────┼────────────────┼────────────────┤
│ MYH 2024/1000 │             2024 │ false   │ Changemaker Educations AB               │ Futuregames Accessible Game Production                                   │ Juridik                                      │       25 │                        0 │ Stockholm    │ Stockholm │              3 │ true           │
│ MYH 2024/1000 │             2024 │ false   │ Changemaker Educations AB               │ Futuregames Accessible Game Production                                   │ Juridik                                      │       25 │                        0 │ Norrbotten   │ Boden     │              3 │ true           │
│ MYH 2024/1000 │             2024 │ false   │ Changemaker Educations AB               │ Futuregames Accessible Game Production                                   │ Juridik                                      │       25 │                        0 │ Skåne        │ Malmö     │              3 │ true           │
│ MYH 2024/1001 │             2024 │ false   │ Changemaker Educations AB               │ Futuregames Inclusive Game Development                                   │ Ekonomi, administration och försäljning      │       25 │                        0 │ Norrbotten   │ Boden     │              3 │ true           │
│ MYH 2024/1001 │             2024 │ false   │ Changemaker Educations AB               │ Futuregames Inclusive Game Development                                   │ Ekonomi, administration och försäljning      │       25 │                        0 │ Stockholm    │ Stockholm │              3 │ true           │
│ MYH 2024/1001 │             2024 │ false   │ Changemaker Educations AB               │ Futuregames Inclusive Game Development                                   │ Ekonomi, administration och försäljning      │       25 │                        0 │ Skåne        │ Malmö     │              3 │ true           │
│ MYH 2024/1002 │             2024 │ false   │ Båstads kommun Akademi Båstad           │ Ekosystemtjänster i praktiken                                            │ Lantbruk, djurvård, trädgård, skog och fiske │       50 │                        0 │ Skåne        │ Båstad    │              1 │ false          │
│ MYH 2024/1003 │             2024 │ false   │ Båstads kommun Akademi Båstad           │ Hållbar dagvattenhantering i praktiken                                   │ Lantbruk, djurvård, trädgård, skog och fiske │       50 │                        0 │ Skåne        │ Båstad    │              1 │ false          │
│ MYH 2024/1004 │             2024 │ false   │ Båstads kommun Akademi Båstad           │ Invasiva växter i utemiljöer                                             │ Lantbruk, djurvård, trädgård, skog och fiske │       25 │                        0 │ Skåne        │ Båstad    │              1 │ false          │
│ MYH 2024/1006 │             2024 │ false   │ Stiftelsen Stockholms Tekniska Institut │ Infrastrukturplanering och strategi                                      │ Samhällsbyggnad och byggteknik               │       50 │                        0 │ Stockholm    │ Stockholm │              1 │ false          │
│      ·        │               ·  │  ·      │            ·                            │                  ·                                                       │               ·                              │        · │                        · │     ·        │     ·     │              · │   ·            │
│      ·        │               ·  │  ·      │            ·                            │                  ·                                                       │               ·                              │        · │                        · │     ·        │     ·     │              · │   ·            │
│      ·        │               ·  │  ·      │            ·                            │                  ·                                                       │               ·                              │        · │                        · │     ·        │     ·     │              · │   ·            │
│ MYH 2024/990  │             2024 │ true    │ Företagsuniversitetet AB                │ Upphandling av digitaliserings- och IT-lösningar                         │ Ekonomi, administration och försäljning      │       15 │                       50 │ Stockholm    │ Stockholm │              1 │ false          │
│ MYH 2024/993  │             2024 │ true    │ INSU AB                                 │ Solenergiprojektering                                                    │ Samhällsbyggnad och byggteknik               │       95 │                       50 │ Södermanland │ Nyköping  │              1 │ false          │
│ MYH 2024/994  │             2024 │ true    │ Företagsuniversitetet AB                │ Att bygga en informationssäkerhetskultur                                 │ Säkerhetstjänster                            │       25 │                       50 │ Stockholm    │ Stockholm │              1 │ false          │
│ MYH 2024/995  │             2024 │ true    │ Hyper Island Program AB - Stockholm     │ Data Analytics                                                           │ Data/IT                                      │       55 │                      100 │ Stockholm    │ Stockholm │              1 │ false          │
│ MYH 2024/996  │             2024 │ false   │ INSU AB                                 │ Solteknik- installation, säkerhet och regelverk                          │ Teknik och tillverkning                      │       60 │                        0 │ Södermanland │ Nyköping  │              1 │ false          │
│ MYH 2024/997  │             2024 │ false   │ INSU AB                                 │ Säkerhetsprojektering- brand-, inbrott-, kamera- och passageanläggningar │ Säkerhetstjänster                            │       95 │                        0 │ Södermanland │ Nyköping  │              1 │ false          │
│ MYH 2024/998  │             2024 │ true    │ Campus Nyköping                         │ Hälsofrämjande och pedagogiska insatser med häst                         │ Lantbruk, djurvård, trädgård, skog och fiske │       50 │                       24 │ Södermanland │ Nyköping  │              1 │ false          │
│ MYH 2024/999  │             2024 │ false   │ Changemaker Educations AB               │ Futuregames Accessible Game Design                                       │ Data/IT                                      │       25 │                        0 │ Stockholm    │ Stockholm │              3 │ true           │
│ MYH 2024/999  │             2024 │ false   │ Changemaker Educations AB               │ Futuregames Accessible Game Design                                       │ Data/IT                                      │       25 │                        0 │ Norrbotten   │ Boden     │              3 │ true           │
│ MYH 2024/999  │             2024 │ false   │ Changemaker Educations AB               │ Futuregames Accessible Game Design                                       │ Data/IT                                      │       25 │                        0 │ Skåne        │ Malmö     │              3 │ true           │
├───────────────┴──────────────────┴─────────┴─────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────┴──────────────────────────┴──────────────┴───────────┴────────────────┴────────────────┤
│ 1202 rows (20 shown)                                                                                                                                                                                                                                                                                   12 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘